### ISSUE TITLE
[RFC][WMS] OCA apps

### ISSUE THREAD

**Issue by jgrandguillaume** [OCA/wms#1]
Hi,

We're working at @camptocamp on Odoo logistic projects since a while and we also have an on-going important project to replace an existing WMS. I though it might be the time to build up an OCA WMS apps. 

Before proposing this, I 've been in touch with Odoo to first ask if they want to implement some of the foreseen features in the core. After some talks with them, it turns out they won't do it (too complex, not fit their strategy, etc..)

Here is the first draft document that try to define the features list: https://docs.google.com/document/d/1mct6bFFWJqW01wGFcjc-uQNEjyCxvh6Y9TuFdRhe-b0/edit#

# Linked issues

- [x] [Split warehouse operations in relevant picking type OCA/stock-logistics-warehouse#640](https://github.com/OCA/stock-logistics-warehouse/issues/640)
  - [x] stock_picking_zone OCA/stock-logistics-warehouse#639 
  - [x] stock_picking_completion_info OCA/stock-logistics-warehouse#693
  - [x] stock_dynamic_routing OCA/stock-logistics-warehouse#788
- [ ] [Vertical automated storage interface OCA/stock-logistics-warehouse#641](https://github.com/OCA/stock-logistics-warehouse/issues/641)
  - [ ] stock_vertical_lift OCA/stock-logistics-warehouse#633
- [ ] [Warehouse map and location attributes](https://github.com/OCA/stock-logistics-warehouse/issues/654)
  - [x] stock_location_zone OCA/stock-logistics-warehouse#653
  - [ ] rework stock_location_zone OCA/stock-logistics-warehouse#711
  - [ ] add stock_location_attribute (split from stock_location_zone) OCA/stock-logistics-warehouse#712
  - [ ] Add stock_location_bin_name (split from stock_location_zone) OCA/stock-logistics-warehouse#713
- [ ] [Goods Reservation: Zone preference & packging](https://github.com/OCA/stock-logistics-warehouse/issues/685)
  - [ ] stock_reserve_rule OCA/stock-logistics-warehouse#683 
  - [ ] stock_reserve_packaging OCA/stock-logistics-warehouse#695 
- [ ] [Virtual reservation](https://github.com/OCA/stock-logistics-warehouse/issues/710)
  - [ ] stock_virtual_reservation OCA/stock-logistics-warehouse#709
- [ ] [Minimum shelf life on reservation](https://github.com/OCA/stock-logistics-warehouse/issues/722)
  - [ ] stock_minimum_shelf_life https://github.com/OCA/stock-logistics-warehouse/pull/723)
- [ ] [Put away rules and ABC classification support](https://github.com/OCA/stock-logistics-warehouse/issues/691)
  - [ ] stock_move_location_dest_constraint_base OCA/stock-logistics-warehouse#696 
  - [ ] stock_move_location_dest_constraint_empty OCA/stock-logistics-warehouse#697 
  - [ ] stock_move_location_dest_constraint_tag OCA/stock-logistics-warehouse#698
  - [ ] stock_putaway_abc OCA/stock-logistics-warehouse#699
  - [ ] stock_putaway_abc_move_location_dest_constraint OCA/stock-logistics-warehouse#700
  - [ ] stock_putaway_product_form OCA/stock-logistics-warehouse#702 
  - [ ] stock_putaway_abc_product_form OCA/stock-logistics-warehouse#703 
  - [ ] stock_putaway_recursive OCA/stock-logistics-warehouse#706 
  - [ ] stock_putaway_rule OCA/stock-logistics-warehouse#707
- [x] [Service definition policies](https://github.com/OCA/stock-logistics-warehouse/issues/694)
  - [x] TODO Add related PR
- [x] [Delivery round](https://github.com/OCA/delivery-carrier/issues/224)
  - [x] TODO: Add related PR

Keep it mind that the main goal here is for us to cover our customer needs and we will try to release a first viable version here. 

We wanted to share it ASAP with you all in order for you to comments, participate and contribute to it if you feel the will !

I will keep you updated in this issue about our progress. Feel free to participate.

Best regards,

Joël

**Comment by bealdav** [comment]
Hi @jgrandguillaume, just a naive question.

I assume this repo is the final destination of some of them list here : those strictly used for advanced stock usage aka wms, i.e. stock_vertical_lift

Is it defined to rename those for `wms_` prefix instead of `stock_` ?
If yes it could be a clean separation between advanced stock usage (dedicated activity) and conventional stock management associated to companies.
What do you think ?

**Comment by larshalvoraam** [comment]
I will be happy to review and assist in testing.

**Comment by jgrandguillaume** [comment]
I close this one as we move to pilot phase now. Track progress here https://github.com/OCA/wms/issues/29
